server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto

spring:
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

###############################
# Spring-Boot Actuators Endpoints
###############################
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

info:
 build:
  name: @project.name@
  description: @project.description@
  version: @project.version@

saml:
  sso:
    metadata-generator:
      entity-base-url: https://dev-sample-isv.devappdirect.me/
      entity-id: https://dev-sample-isv.devappdirect.me/saml/metadata